/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.vehicle.view;

import ec.edu.espe.vehicle.controller.VehicleController;
import ec.edu.espe.vehicle.model.Vehicle;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author < Jennifer Beltran Team of machine Developers>
 */
public class FrmVehicle extends javax.swing.JFrame {

    /**
     * Creates new form FrmVehicle
     */
    public FrmVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Pnlinput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLaVehicle = new javax.swing.JLabel();
        jLaMileAge = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLVehicle = new javax.swing.JLabel();
        TxtCodeVehicle = new javax.swing.JTextField();
        RbtBrand = new javax.swing.JRadioButton();
        RbtBrand1 = new javax.swing.JRadioButton();
        RbtBrand2 = new javax.swing.JRadioButton();
        RbtBrand3 = new javax.swing.JRadioButton();
        RbtType = new javax.swing.JRadioButton();
        RbtType1 = new javax.swing.JRadioButton();
        RbtType2 = new javax.swing.JRadioButton();
        JprPrice = new javax.swing.JTextField();
        jRaRed = new javax.swing.JRadioButton();
        jRaBlue = new javax.swing.JRadioButton();
        jRaGriss = new javax.swing.JRadioButton();
        TextMile = new javax.swing.JTextField();
        TextAmount = new javax.swing.JTextField();
        BtnNew = new javax.swing.JRadioButton();
        BtnUsed = new javax.swing.JRadioButton();
        jBtSave = new javax.swing.JButton();
        jBtDelete = new javax.swing.JButton();
        jBtExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnlinput.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("VEHICLE DEALERSHIP");

        jLabel2.setText("Code Vehicle: ");

        jLabel3.setText("Brand Vehicle: ");

        jLabel4.setText("Type Vehicle: ");

        jLabel5.setText("Price Vehicle: ");

        jLaVehicle.setText("Color Vehicle");

        jLaMileAge.setText("Mile age Vehicle: ");

        jLabel8.setText("Amount of Sale: ");

        jLVehicle.setText("Vehicle Sold: ");

        RbtBrand.setText("Chevrolet");
        RbtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtBrandActionPerformed(evt);
            }
        });

        RbtBrand1.setText("Toyota");

        RbtBrand2.setText("Kia");
        RbtBrand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtBrand2ActionPerformed(evt);
            }
        });

        RbtBrand3.setText("Hyundai");
        RbtBrand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtBrand3ActionPerformed(evt);
            }
        });

        RbtType.setText("Vehicle");
        RbtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtTypeActionPerformed(evt);
            }
        });

        RbtType1.setText("Truck");

        RbtType2.setText("Motorcycle");

        jRaRed.setText("Red");

        jRaBlue.setText("Blue");

        jRaGriss.setText("Griss");

        BtnNew.setText("New");

        BtnUsed.setText("Used");

        jBtSave.setText("Save");
        jBtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSaveActionPerformed(evt);
            }
        });

        jBtDelete.setText("Delete");
        jBtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDeleteActionPerformed(evt);
            }
        });

        jBtExit.setText("Exit");
        jBtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlinputLayout = new javax.swing.GroupLayout(Pnlinput);
        Pnlinput.setLayout(PnlinputLayout);
        PnlinputLayout.setHorizontalGroup(
            PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlinputLayout.createSequentialGroup()
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlinputLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlinputLayout.createSequentialGroup()
                                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(PnlinputLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jBtSave)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbtBrand3)
                                    .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jBtExit)
                                        .addGroup(PnlinputLayout.createSequentialGroup()
                                            .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(RbtBrand1)
                                                .addComponent(RbtBrand2)
                                                .addGroup(PnlinputLayout.createSequentialGroup()
                                                    .addComponent(RbtBrand)
                                                    .addGap(141, 141, 141)
                                                    .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRaGriss)
                                                        .addComponent(jLabel4))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(RbtType2)
                                                .addComponent(RbtType1)
                                                .addComponent(RbtType))))))
                            .addGroup(PnlinputLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(JprPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlinputLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCodeVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PnlinputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLaVehicle)
                            .addComponent(jLaMileAge))
                        .addGap(18, 18, 18)
                        .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextMile, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlinputLayout.createSequentialGroup()
                                .addComponent(jRaRed)
                                .addGap(54, 54, 54)
                                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtDelete)
                                    .addComponent(jRaBlue)))))
                    .addGroup(PnlinputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLVehicle)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNew)
                            .addComponent(BtnUsed)))
                    .addGroup(PnlinputLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PnlinputLayout.setVerticalGroup(
            PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlinputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TxtCodeVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RbtBrand)
                    .addComponent(jLabel4)
                    .addComponent(RbtType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbtType1)
                    .addComponent(RbtBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtBrand2)
                    .addComponent(RbtType2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbtBrand3)
                .addGap(13, 13, 13)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JprPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLaVehicle)
                    .addComponent(jRaRed)
                    .addComponent(jRaBlue)
                    .addComponent(jRaGriss))
                .addGap(18, 18, 18)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLaMileAge)
                    .addComponent(TextMile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(TextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVehicle)
                    .addComponent(BtnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnUsed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(PnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtSave)
                    .addComponent(jBtDelete)
                    .addComponent(jBtExit))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pnlinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnlinput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jBtExitActionPerformed

    private void jBtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtSaveActionPerformed

    private void RbtBrand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtBrand3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtBrand3ActionPerformed

    private void RbtBrand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtBrand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtBrand2ActionPerformed

    private void RbtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtBrandActionPerformed
        Vehicle vehicle;
        VehicleController vehicleController;
        String CodeVehicle = TxtCodeVehicle.getText();
        String BrandVehicle  = RbtBrand.getSelectedIcon().toString();
        String TypeVehicle  = RbtType.getSelectedIcon().toString();
        String PriceVehicle  = JprPrice.getText();
        String ColorVehicle = jRaRed.getSelectedIcon().toString();
        String MileageVehicle = TextMile.getText();
        String AmountofSale  = TextAmount.getText();
        String VehicleSold  = BtnNew.getSelectedIcon().toString();

        ArrayList<Vehicle> vehicles = new ArrayList<>();
        int monthIkew = 3;

        //Vehicle vehicle = new vehicle(CodeVehicle,BrandVehicle,TypeVehicle,PriceVehicle,ColorVehicle,MileageVehicle,AmountofSale,VehicleSold);

        //contactController = new ContactController(contact, this);
        //contactController.add(contact);

        JOptionPane.showMessageDialog(rootPane, "adding + " + TxtCodeVehicle.getName());
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtBrandActionPerformed

    private void RbtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtTypeActionPerformed

    private void jBtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDeleteActionPerformed
      TxtCodeVehicle.setText("");
      RbtBrand.setText("");
      RbtType.setText("");
      JprPrice.setText("");
      jRaRed.setText("");
      TextMile.setText("");
      TextAmount.setText("");
      BtnNew.setText("");
    }//GEN-LAST:event_jBtDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnNew;
    private javax.swing.JRadioButton BtnUsed;
    private javax.swing.JTextField JprPrice;
    private javax.swing.JPanel Pnlinput;
    private javax.swing.JRadioButton RbtBrand;
    private javax.swing.JRadioButton RbtBrand1;
    private javax.swing.JRadioButton RbtBrand2;
    private javax.swing.JRadioButton RbtBrand3;
    private javax.swing.JRadioButton RbtType;
    private javax.swing.JRadioButton RbtType1;
    private javax.swing.JRadioButton RbtType2;
    private javax.swing.JTextField TextAmount;
    private javax.swing.JTextField TextMile;
    private javax.swing.JTextField TxtCodeVehicle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jBtDelete;
    private javax.swing.JButton jBtExit;
    private javax.swing.JButton jBtSave;
    private javax.swing.JLabel jLVehicle;
    private javax.swing.JLabel jLaMileAge;
    private javax.swing.JLabel jLaVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRaBlue;
    private javax.swing.JRadioButton jRaGriss;
    private javax.swing.JRadioButton jRaRed;
    // End of variables declaration//GEN-END:variables
}
